name: 'tilemaker'
description: 'Make OpenStreetMap vector tiles without the stack'
inputs:
  input:
    description: 'An .osm.pbf file from planet extract, as typically downloaded from providers like Geofabrik'
    required: true
  config:
    description: 'A JSON file listing each layer, and the zoom levels at which to apply it'
    required: false
    default: 'config.json'
  process:
    description: "A Lua program that looks at each node/way's tags, and places it into layers accordingly"
    required: false
    default: 'process.lua'
  output:
    description: 'Could be directory of tiles, or a .mbtiles files'
    required: true
  extra:
    description: 'Other options for tilemaker'
    required: false
    default: '--verbose'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/systemed/tilemaker:master'
  args:
    - --input=${{ inputs.input }}
    - --config=${{ inputs.config }}
    - --process=${{ inputs.process }}
    - --output=${{ inputs.output }}
    - ${{ inputs.extra }}
