/*! \file */ 
#ifndef _OSM_MEM_TILES
#define _OSM_MEM_TILES

#include "tile_data.h"
#include "osm_store.h"
#include "geometry_cache.h"

// NB: Currently, USE_NODE_STORE and USE_WAY_STORE are equivalent.
// If we permit LayerAsCentroid to be generated from the OSM stores,
// this will have to change.
#define OSM_THRESHOLD (1ull << 35)
#define USE_NODE_STORE (1ull << 35)
#define IS_NODE(x) (((x) >> 35) == (USE_NODE_STORE >> 35))
#define USE_WAY_STORE (1ull << 35)
#define IS_WAY(x) (((x) >> 35) == (USE_WAY_STORE >> 35))
#define OSM_ID(x) ((x) & 0b11111111111111111111111111111111111)

class NodeStore;
class WayStore;

/**
	\brief OsmMemTiles stores OSM objects in memory and provides a vector of OutputObjectf for specified tiles
	
	The input objects are generated by PbfReader. The output objects are sent to OsmMemTiles for storage.

	This class provides a consistent interface for Lua scripts to access.
*/
class OsmMemTiles : public TileDataSource {

public:
	OsmMemTiles(
		size_t threadNum,
		uint baseZoom,
		bool includeID,
		const NodeStore& nodeStore,
		const WayStore& wayStore
	);

	Geometry buildWayGeometry(
		const OutputGeometryType geomType, 
		const NodeID objectID,
		const TileBbox &bbox
	) override;
	LatpLon buildNodeGeometry(OutputGeometryType const geomType, NodeID const objectID, const TileBbox &bbox) const override;


	void Clear();

private:
	void populateLinestring(Linestring& ls, NodeID objectID);
	Linestring& getOrBuildLinestring(NodeID objectID);
	void populateMultiPolygon(MultiPolygon& dst, NodeID objectID) override;

	const NodeStore& nodeStore;
	const WayStore& wayStore;
};

#endif //_OSM_MEM_TILES

